# Generated by Django 3.1 on 2020-08-15 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(choices=[('new', 'new'), ('in_progress', 'in_progress'), ('done', 'done')], default='new', max_length=125)),
                ('link_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_tasks', to='tasks.task')),
            ],
        ),
    ]
